[tests] [integration-tests] 603: add describe pod, exit 1 after output debug info
Signed-off-by: Nikita B <n2h9z4@gmail.com>

diff --git a/.github/workflows/integration-tests-ci.yml b/.github/workflows/integration-tests-ci.yml
--- a/.github/workflows/integration-tests-ci.yml
+++ b/.github/workflows/integration-tests-ci.yml
@@ -50,7 +50,10 @@ jobs:
       - name: Integration tests set up
         run: make integration-tests-setup
       - name: Integration tests print setup debug output
-        run: make integration-tests-setup-debug-output
+        run: |
+          make integration-tests-setup-debug-output
+          echo "Integration tests setup failed - stopping workflow"
+          exit 1
         if: failure()
       - name: Integration tests run
         run: make integration-tests-run
